# Bài 1

In [ ]:
import pandas as pd
import sympy as sp
import numpy as np

In [ ]:
A = np.zeros((3,4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
B = np.ones((2,4))
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:

C = np.full((5, 4), 5)
C


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:

D = np.identity(5)
D


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:

E = np.random.rand(4, 6)
E

array([[0.48051545, 0.08202091, 0.58738358, 0.31298579, 0.41825801,
        0.29172687],
       [0.74057035, 0.93610698, 0.37221022, 0.29250713, 0.85208089,
        0.38965521],
       [0.94677994, 0.78776767, 0.16640998, 0.92686984, 0.83403186,
        0.96011261],
       [0.51559352, 0.02632799, 0.4175776 , 0.9160556 , 0.34745294,
        0.57476457]])

In [ ]:
B = np.zeros((5, 5), dtype=int)
for i in range(5):
    for j in range(5):
        if (i == j):
          B[i,j] = 1
B

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:

A_T =np.linalg.det(A)
print("Định thức của ma trận A : ", A_T)

Định thức của ma trận A :  1.0


In [ ]:
B_T = np.linalg.det(B)
print("Định thức của ma trận B : ", B_T)

Định thức của ma trận B :  0.0


In [ ]:
AB = np.dot(A,B)
print("A*B =",AB)

A*B = [[ 0.  1.  2.  3.  4.]
 [ 2.  3.  4.  5.  6.]
 [ 4.  5.  6.  7.  8.]
 [ 6.  7.  8.  9. 10.]
 [ 8.  9. 10. 11. 12.]]


In [ ]:
A_B = np.add(A,B)
print("A+B = ",A_B)

A+B =  [[ 1.  1.  2.  3.  4.]
 [ 2.  4.  4.  5.  6.]
 [ 4.  5.  7.  7.  8.]
 [ 6.  7.  8. 10. 10.]
 [ 8.  9. 10. 11. 13.]]


In [ ]:
A_B1 = np.subtract(A,B)
print("A-B = ", A_B1)

A-B =  [[  1.  -1.  -2.  -3.  -4.]
 [ -2.  -2.  -4.  -5.  -6.]
 [ -4.  -5.  -5.  -7.  -8.]
 [ -6.  -7.  -8.  -8. -10.]
 [ -8.  -9. -10. -11. -11.]]


In [ ]:
result = np.multiply(4, np.divide(A, B))
result


<ipython-input-47-14e794bd834a>:1: RuntimeWarning: divide by zero encountered in divide
  result = np.multiply(4, np.divide(A, B))


array([[       inf, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.33333333, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.44444444, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.33333333]])

In [ ]:
# a. Ma trận A[3,4] toàn giá trị 0
matrix_a = [[0, 0, 0, 0],
            [0, 0, 0, 0],
            [0, 0, 0, 0]]

# b. Ma trận B[2,4] toàn giá trị 1
matrix_b = [[1, 1, 1, 1],
            [1, 1, 1, 1]]

# c. Ma trận C[4,4] toàn giá trị 5
matrix_c = [[5, 5, 5, 5],
            [5, 5, 5, 5],
            [5, 5, 5, 5],
            [5, 5, 5, 5]]

# d. Ma trận D[5,5] với các giá trị trên đường chéo chính là 1
matrix_d = [[1, 0, 0, 0, 0],
            [0, 1, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1]]

# e. Ma trận E[4,6] với các giá trị ngẫu nhiên
import random
matrix_e = [[random.random() for _ in range(6)] for _ in range(4)]

# In các ma trận
print("Matrix A:")
for row in matrix_a:
    print(row)

print("\nMatrix B:")
for row in matrix_b:
    print(row)

print("\nMatrix C:")
for row in matrix_c:
    print(row)

print("\nMatrix D:")
for row in matrix_d:
    print(row)

print("\nMatrix E:")
for row in matrix_e:
    print(row)

Matrix A:
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]

Matrix B:
[1, 1, 1, 1]
[1, 1, 1, 1]

Matrix C:
[5, 5, 5, 5]
[5, 5, 5, 5]
[5, 5, 5, 5]
[5, 5, 5, 5]

Matrix D:
[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

Matrix E:
[0.5687334666974101, 0.506538430719895, 0.6904158533915538, 0.8609660246664289, 0.21091620096358532, 0.8489212809965877]
[0.9952498047508264, 0.7569850275276003, 0.8858999925508021, 0.5441273182146792, 0.3151688635544704, 0.07570366734993472]
[0.27234942500325554, 0.7760782091441799, 0.126282281112442, 0.20424143200135214, 0.46154725299751875, 0.4512795712574281]
[0.43199054999872766, 0.9069250139175102, 0.8171341152822059, 0.1548914388485617, 0.0553100579185537, 0.009511008137106591]


# Bài 2

In [ ]:
#Một sọt Cam có 10 trái trong đó có 4 trái hư. Lấy ngẫu nhiên ra ba trái. a) Tính xác suất lấy được 3 trái hư.

from scipy.stats import binom
p = 0.4
n = 3
k = 3
print(binom.pmf(k, n, p))


0.06400000000000002


P(X = 3) = (4C3 *6C0)/ 10C3

In [ ]:
# b) Tính xác suất lấy được 1 trái hư.

p = 0.4
n = 3
k = 1
print(binom.pmf(k, n, p))


0.43199999999999994


P(X=1) = (4C1 * 6C2)/10C3

In [ ]:
# c) Tính xác suất lấy được ít nhất một trái hư.

p = 0.4
n = 3
k = 0
print(1 - binom.pmf(k, n, p))


0.784


P(X>=1) = 1 - P(X=0) = 1 - (4C0*6C3)/10C3

In [ ]:
#  d) Tính xác suất lấy được nhiều nhất 2 trái hư.

p = 0.4
n = 3
k = 2
print(binom.cdf(k, n, p) - binom.cdf(k-1, n, p))


0.28800000000000003


P(0<=X<=2) = P(X=0) + P(X=1) + P(X=2) = (4C0*6C3)/10C3 + (4C1 * 6C2)/10C3 + (4C2 * 6C1 )/10C3

In [ ]:
# a) Tính xác suất lấy được 3 trái hư
p_hu = 4 / 10  # Xác suất trái hư
p_3_hu = (p_hu ** 3) * ((1 - p_hu) ** 0)
print("a) Xác suất lấy được 3 trái hư:", p_3_hu)

# b) Tính xác suất lấy được 1 trái hư
p_1_hu = (p_hu ** 1) * ((1 - p_hu) ** 2)
print("b) Xác suất lấy được 1 trái hư:", p_1_hu)

# c) Tính xác suất lấy được ít nhất một trái hư
p_at_least_1_hu = 1 - ((1 - p_hu) ** 3)
print("c) Xác suất lấy được ít nhất một trái hư:", p_at_least_1_hu)

# d) Tính xác suất lấy được nhiều nhất 2 trái hư
p_at_most_2_hu = 1 - (p_hu ** 3) - 3 * (p_hu ** 2) * (1 - p_hu)
print("d) Xác suất lấy được nhiều nhất 2 trái hư:", p_at_most_2_hu)


a) Xác suất lấy được 3 trái hư: 0.06400000000000002
b) Xác suất lấy được 1 trái hư: 0.144
c) Xác suất lấy được ít nhất một trái hư: 0.784
d) Xác suất lấy được nhiều nhất 2 trái hư: 0.6479999999999999


# bài 3

In [ ]:

n = 10
p = 0.5
k = 0
print(binom.pmf(k, n, p))


0.0009765624999999989


P(X=0) = (1-P)^10 = (1-1/2)^10

In [ ]:

n = 10
p = 0.5
k = 5
print(binom.pmf(k, n, p))


0.24609375000000003


P(X=5) = 10C5 * (1/2)^5 *(1/2)^5

In [ ]:
# c) Số trai từ 5 đến 7.

n = 10
p = 0.5
k = np.arange(5, 8)
print(binom.pmf(k, n, p))


[0.24609375 0.20507812 0.1171875 ]


P(5≤X≤7)=P(X=5)+P(X=6)+P(X=7)


P(5≤X≤7)=C(10,5)⋅(2,1) 5⋅(2,1)5 +C(10,6)⋅(2,1)6⋅(2,1)4 +C(10,7)⋅(2,1)7⋅(2,1) 3


In [ ]:
n_children = 10
p_boy = 0.5

# a) Không có con trai
p_no_boy = (1 - p_boy) ** n_children
print("a) Xác suất không có con trai:", p_no_boy)

# b) Có 5 con trai và 5 con gái
p_5_boys_5_girls = (p_boy ** 5) * ((1 - p_boy) ** 5)
print("b) Xác suất có 5 con trai và 5 con gái:", p_5_boys_5_girls)

# c) Số trai từ 5 đến 7
p_5_to_7_boys = sum((p_boy ** k) * ((1 - p_boy) ** (n_children - k)) for k in range(5, 8))
print("c) Xác suất có từ 5 đến 7 con trai:", p_5_to_7_boys)


a) Xác suất không có con trai: 0.0009765625
b) Xác suất có 5 con trai và 5 con gái: 0.0009765625
c) Xác suất có từ 5 đến 7 con trai: 0.0029296875


#Bài 4

In [ ]:

X_values = [0, 1, 2, 3]
P_X_values = [1/120, 27/120, 72/120, 20/120]

table_data = {'X': X_values, 'P(X)': P_X_values}

print("Bảng phân phối xác suất của X:")
for i in range(len(X_values)):
    print(f"X = {X_values[i]}: P(X) = {P_X_values[i]}")

with open("data.txt", "w") as file:
    file.write("X\tP(X)\n")
    for i in range(len(X_values)):
        file.write(f"{X_values[i]}\t{P_X_values[i]}\n")


In [ ]:
def doc_du_lieu_tu_file(file_path):
    x = []
    f = []

    with open(file_path, 'r') as file:
        next(file)
        for line in file:
            line_data = line.strip().split('\t')
            x.append(int(line_data[0]))
            f.append(float(line_data[1]))

    return x, f

file_path = 'data.txt'
x, f = doc_du_lieu_tu_file(file_path)

ky_vong_disc = ky_vong(x, f)
print(f"Kỳ vọng (E(X) or μ): {ky_vong_disc}")

phuong_sai_disc = phuong_sai(x, f)
print(f"Phương sai (σ² or V(x)): {phuong_sai_disc}")

do_lech_chuan_disc = do_lech_chuan(x, f)
print(f"Độ lệch chuẩn (σ or SD(X)): {do_lech_chuan_disc}")


In [ ]:
from scipy.stats import rv_continuous

class phan_phoi(rv_continuous):
    def _pdf(self, x):
        k = 1/900
        if 0 <= x <= 30:
            return k * (30 - x)
        return 0

X_continuous_rv = phan_phoi(a=0, b=30)

ky_vong_continuous_lib = X_continuous_rv.mean()
phuong_sai_continuous_lib = X_continuous_rv.var()
do_lech_chuan_continuous_lib = X_continuous_rv.std()

print("Kỳ vọng: {:.2f}".format(ky_vong_continuous_lib))
print("Phương sai: {:.2f}".format(phuong_sai_continuous_lib))
print("Độ lệch chuẩn: {:.2f}".format(do_lech_chuan_continuous_lib))


b. Sử dụng thư viện:
   Kỳ vọng: 3.0
   Phương sai: 0.0
   Độ lệch chuẩn: 0.0


# bài 5

#a

In [ ]:
import math

# Dữ liệu
n1 = 100
n2 = 100
p1 = 0.18
p2 = 0.10
z = 1.96

SE = math.sqrt((p1*(1-p1)/n1) + (p2*(1-p2)/n2))

ME = z * SE

diff = p1 - p2
CI = (diff - ME, diff + ME)

CI



(-0.015538691638518898, 0.17553869163851887)

In [ ]:
import statsmodels.api as sm
import numpy as np

n1 = 100
n2 = 100
p1 = 0.18
p2 = 0.10

count = np.array([p1 * n1, p2 * n2])
nobs = np.array([n1, n2])

z_score, p_value = sm.stats.proportions_ztest(count, nobs)

ci = sm.stats.proportion_confint(count, nobs)

z_score, p_value, ci


(1.6302782918784444,
 0.10304269342469359,
 (array([0.10470064, 0.04120108]), array([0.25529936, 0.15879892])))

#b

In [ ]:
n_25_59 = 2000
n_60_plus = 100
p_25_59 = (0.93 + 0.95) / 2
p_60_plus = 0.93
z = 1.96
SE_diff = math.sqrt((p_25_59*(1-p_25_59)/n_25_59) + (p_60_plus*(1-p_60_plus)/n_60_plus))

ME_diff = z * SE_diff

diff = p_25_59 - p_60_plus
CI_diff = (diff - ME_diff, diff + ME_diff)

CI_diff


(-0.04108047298136548, 0.06108047298136528)

In [ ]:
import statsmodels.api as sm
import numpy as np

n_25_59 = 2000
n_60_plus = 100
p_25_59 = (0.93 + 0.95) / 2
p_60_plus = 0.93

count_diff = np.array([p_25_59 * n_25_59, p_60_plus * n_60_plus])
nobs_diff = np.array([n_25_59, n_60_plus])

z_score_diff, p_value_diff = sm.stats.proportions_ztest(count_diff, nobs_diff)

ci_diff = sm.stats.proportion_confint(count_diff, nobs_diff)

z_score_diff, p_value_diff, ci_diff


(0.4094107502265574,
 0.6822382517612233,
 (array([0.92959187, 0.8799921 ]), array([0.95040813, 0.9800079 ])))

#Bài 6

In [ ]:
import math

Z = 1.645
E = 0.04
p_hat = 0.5
n = math.ceil((Z**2 * p_hat * (1 - p_hat)) / E**2)

n


423


# Bài 7



Lò̀i giai Cho $1.96 \sigma_{\left(\bar{x}_1-\bar{x}_2\right)}$ bằng với $B=1$ phút, chúng ta có được
$$
1.96 \sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}=1
$$

Bời vì chúng ta mong muốn $n_1$ bằng với $n_2$, chúng ta có thể đặt $n_1=n_2=n$ và có được phương trinh
$$
1.96 \sqrt{\frac{\sigma_1^2}{n}+\frac{\sigma_2^2}{n}}=1
$$

Như đã được lưu ý ở trên, độ biến thiên (dãy = range = max - min) của từng phương pháp lắp ráp xấp xỉ như nhau, và vì thế $\sigma_1^2=\sigma_2^2=\sigma^2$. Bởi vì dãy này, bằng với 8 phút, là xấp xi bằng với $4 \sigma$, cho nên
$$
4 \sigma \approx 8
$$
và
$$
\sigma \approx 2
$$

Thay thế giá trị này cho $\sigma_1$ và $\sigma_2$ trong phương trinh trên, chúng ta có được
$$
1.96 \sqrt{\frac{(2)^2}{n}+\frac{(2)^2}{n}}=1
$$
hay
$$
1.96 \sqrt{\frac{8}{n}}=1
$$
và
$$
\sqrt{n}=1.96 \sqrt{8}
$$

Giải ra, chúng ta có $n=31$. Như vậy mỗi nhóm nên có xấp xỉ $n=31$ công nhân.

In [39]:
import math

def calculate_sample_size(sigma, margin_of_error, confidence_level):
    z_value = 1.96
    sample_size = math.ceil((z_value * sigma / margin_of_error)**2)

    return sample_size

sigma = 2
margin_of_error = 1
confidence_level = 0.95

sample_size = calculate_sample_size(sigma, margin_of_error, confidence_level)
print(f"Số lượng công nhân cần thiết cho mỗi nhóm: {sample_size}")


Số lượng công nhân cần thiết cho mỗi nhóm: 16
